kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: docker/compose
    commands:
      - echo $DOCKER_HOST
      - cp .env.example .env
      - docker-compose -v
      - ls
      - docker-compose up --build

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock