kind: pipeline
name: cicd

steps:
  - name: test
    image: docker/compose
    volume:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - echo $DOCKER_HOST
      - cp .env.example .env
      - docker-compose -f docker-compose.yml up -d