version: "3.7"

services:

  php:
    build:
      args:
        user: john
        uid: 1001
      context: ./infra/dev/docker
      dockerfile: php.Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./api:/var/www
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306

  nginx:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./api:/var/www
      - ./infra/dev/config/nginx:/etc/nginx/conf.d
    depends_on:
      - php
