# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Api\V1\Controller\TodoController:
        tags: [ controller.service_arguments ]
        bind:
            $queryBus: '@query.bus'

    App\Api\V1\Controller\UserController:
        tags: [ controller.service_arguments ]
        bind:
            $commandBus: '@command.bus'

    League\Fractal\Manager: ~

    App\Todo\Application\Command\CreateBookTodoStrategy: ~
    App\Todo\Application\Command\CreateCourseTodoStrategy: ~
    App\Todo\Application\Command\CreateMediaTodoStrategy: ~

    App\Todo\Application\Todo\Command\CreateTodoCommandStrategy:
        calls:
            - addStrategy: ['@App\Todo\Application\Todo\Command\CreateBookTodoStrategy']
            - addStrategy: ['@App\Todo\Application\Todo\Command\CreateCourseTodoStrategy']
            - addStrategy: ['@App\Todo\Application\Todo\Command\CreateMediaTodoStrategy']
